dist: trusty
sudo: required
before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh
install:
  - . ./install-tex.sh
  - ./tlmgr.sh update --self --all
script:
  - latex test/gotoh_test.tex && diff gotoh_test.dbg test/gotoh_test.txt && rm -f *.dbg
  - xelatex test/gotoh_test.tex && diff gotoh_test.dbg test/gotoh_test.txt && rm -f *.dbg
  - lualatex test/gotoh_test.tex && diff gotoh_test.dbg test/gotoh_test.txt && rm -f *.dbg

